sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20030201
  alioss:
    endpoint: https://oss-us-west-1.aliyuncs.com
    access-key-id: LTAI5tFse5AVZgviPuJNW2BN
    access-key-secret: hbu4HnSmqIQ1YaLXmYBriEmF5cddrQ
    bucket-name: web-tlias-nick-zhang
  redis:
    host: localhost
    port: 6379
    password: 20030201
    database: 10
  wechat:
    appid: wx9f5341a46dbcf87c
    secret: 6fb0bddc4e8938252ef0a376858a4009